# Generated by Django 5.0.7 on 2024-08-03 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='sybmission_date',
            new_name='submission_date',
        ),
    ]
